# In this pipeline, we execute these steps: Plan (planejamento)| Code (código) | Build (compilar aplicação) | Deploy (publicar aplicação)

# This is a basic workflow to help you get started with Actions
name: SegundaPipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job 1 - This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on - Uses GitHub Infrastructure
    runs-on: ubuntu-latest

    # Environment variables
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout 
      - uses: actions/checkout@v4

      # DockerHub Login
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build image
      - name: Build o docker compose 
        run: |
          docker compose build --no-cache
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME}}   
      
      # Send the image to Docker Hub
      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/infnet_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/infnet_backend:latest
  # Job 2 - Continuos Deploy          
  cd:
    # Indicate runner execute inside AWS and that need RUNNER with name 'ci' execute before that
    runs-on: aws    
    needs: [ci]

    # Environment variables
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout 
      - uses: actions/checkout@v4

      # DockerHub Login
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Execute the real deploy
      - name: Subir o docker compose 
        # Get the lastest image version from Docker Hub
        # Forces the recreation of containers even if the image has not been modified
        run: |
          docker compose pull
          docker compose up --force-recreate -d